
services:
  web:
    build: .
    ports:
      - "4242:4242"
    volumes:
      - .:/code
    depends_on:
      - redis
  redis:
     image: redis
     environment:
        # ALLOW_EMPTY_PASSWORD is recommended only for development.
         - ALLOW_EMPTY_PASSWORD=yes
         - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
     ports:
       - '6379:6379'
